export const ADD_STREAMER = 'ADD_STREAMER';
export const DELETE_STREAMER = 'DELETE_STREAMER';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_ISFETCHING = 'SET_ISFETCHING';
